server {
    listen 80;
    server_name carniceria.aedestec.com api-carniceria.aedestec.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name carniceria.aedestec.com;

    ssl_certificate /etc/letsencrypt/live/carniceria.aedestec.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/carniceria.aedestec.com/privkey.pem;

    access_log /var/log/nginx/carniceria-pos-app.access.log;
    error_log /var/log/nginx/carniceria-pos-app.error.log warn;

    client_max_body_size 5m;

    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl http2;
    server_name api-carniceria.aedestec.com;

    ssl_certificate /etc/letsencrypt/live/api-carniceria.aedestec.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api-carniceria.aedestec.com/privkey.pem;

    access_log /var/log/nginx/carniceria-pos-api.access.log;
    error_log /var/log/nginx/carniceria-pos-api.error.log warn;

    client_max_body_size 5m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
